### ISSUE TITLE
Media control missing?

### ISSUE THREAD

**Issue by mewtlu** [sharandac/My-TTGO-Watch#308]
Hi there, apologies if this is just my stupidity but I think I've searched everywhere now and can't find the ability to control media playing on my Gadgetbridge connected device anywhere, neither as an app nor in place of the notes app as it looks like it was moved in [these changes from dervomsee](https://github.com/sharandac/My-TTGO-Watch/pull/255)? Thanks!

**Comment by sharandac** [comment]
No, this is not a stupid question but a good question. The media player was removed from the note again.
Unfortunately, it was also commented out because it interfered with the theme change (see /src/gui/mainbar/setup_tile/bluetooth_settings/bluetooth_settings.c line 130).

It should be active again in the next version.
