### ISSUE TITLE
BatteryView

### ISSUE THREAD

**Issue by KrustyDerClown** [sharandac/My-TTGO-Watch#347]
Hey,

first, nice project!

I had this OS preinstalled from factory on my watch and I had a batteryview tile. 
I then compiled and installed last git version here but did not see any battery information tile anymore.
I looked at the code and saw this  `battery_view_tile_setup( battery_settings_tile_num );` commented out. After comparing with an older version in git, I was able to revert the old behavior to see the battery information in battery settings.

Did this change happen on purpose? if yes why?

BR, Krusty

**Comment by sharandac** [comment]
Most people were confused by the information. That's why the same questions kept coming, that the information is actually wrong, with the same discourse over and over again.
But if you want to, you can just fade in the information again. But then you have to know how to interpret it.
Perhaps one can also insert an option to have the information displayed?
